### ISSUE TITLE
Project Builds Fail After Latest Git Pull

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#39]
I updated my OpenGLAda with GitHub Desktop and later checked with git pull.
Seems to be a problem with OpenGL.Glfw
Now my builds fails with 
Undefined symbols for architecture x86_64:
  "_glfwCreateWindow", referenced from:
      _glfw__windows__init in libGlfwAda.a(glfw-windows.o)
  "_glfwDefaultWindowHints", referenced from:
      _glfw__windows__hints__reset_to_defaults in libGlfwAda.a(glfw-windows-hints.o)
  "_glfwDestroyWindow", referenced from:
      _glfw__windows__destroy in libGlfwAda.a(glfw-windows.o)
etc.

**Comment by rogermc2** [comment]
OpenGL.Glfw build succeeds but Glfw_Test build fails as above.

**Comment by flyx** [comment]
I changed the linker options from `-lglfw3` to `-lglfw` for GLFW 3, because most distributions name the new library version `libglfw` these days. You seem to still have a libglfw lying around which is at GLFW 2, and that lacks the window management functions. You can either change the `Linker_Options` back to `-lglfw3` in `opengl-glfw.gpr` or update your GLFW distribution, whereever you get it from (I use *nix* these days).

**Comment by rogermc2** [comment]
Thanks.
I use Homebrew.
Uninstallling glfw3 then installing glfw fixed the problem.
