### ISSUE TITLE
glNormal3fv not implemented?

### ISSUE THREAD

**Issue by rogermc2** [flyx/OpenGLAda#79]
glNormal3dv seems to be the only glNormal3 implemented.
glNormal3dv is implemented as GL.Immediate.Set_Normal via GL.API.Normal.
Probably not a problem if I use this GL.Immediate.Set_Normal.
However, I notices from  Immediate API in GL-API.spec that Immediate functions are deprecated so I'll try and figure out the current way of using normals.

**Comment by flyx** [comment]
Like most other things in `GL.Immediate`, `glNormal` is provided for different types. However, this does not make any sense since the values are converted to what OpenGL uses internally anyway. That's why I only implemented the `Double` functions.

And as you correctly noticed, `glNormal`, like everything from the immediate API, is deprecated and should not be used since OpenGL 3.
